name: CI/CD Pipeline for pytest and behave tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: pytest
      - name: Test with behave
        run: behave
      - name: Notify to Slack if fails through a webhook
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' https://hooks.slack.com/services/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
