name: CI/CD Pipeline for pytest and behave tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: pytest
      - name: Test with behave
        run: behave
      - name: Notify to Slack if fails through a webhook
        if: failure()
        run: |
          curl -X POST -H 'Content-Type: application/json' \
          --data "{\"text\": \"El pipeline falló en el repo ${{ github.repository }}.\nCommit: ${{ github.sha }}\nAutor: ${{ github.actor }}\"}" \
          https://hooks.slack.com/services/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
